version: '3.1'

services:
  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
    environment:
        LOG_DIR: /tmp/logs
    ports:
      - 2181:2181                 # Zookeeper
    
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
    depends_on:
      - zookeeper    
    environment:
        LOG_DIR: /tmp/logs
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092                 # Kafka