apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQVUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIaGNOTWpFeApNakV3TVRnek5UTTNXaGNOTXpFeE1qQTRNVGd6TlRNM1dqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM5OGhXWlgySnl6WXNteFF5WlMwWExyT2diamczbXRyU3hxUmhmQXltUwpvYWtIa2MydkdDcjlpYm9VRklyeXRqTzROMUswUEF1cjR1RFZEZlQzUXlkbm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVNlJGN0pPcWJJTmxjNU5iNW4wZUwKYVExVVQzTXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdjZWl0ai9GdDl3U3E5NW9oUE1BV0gvT1dZQis2SHJxYQpPQUc4dmE0c3p1b0NJUUNzRmViQXBWZkRZQzZQdXplZmdmQ1FHUEtDN1p1ZWJmb0d2YVlMWkQzWnVnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    server: https://consola.labgdevops.movistar.com.ar/k8s/clusters/local
  name: local
contexts:
- context:
    cluster: local
    namespace: strange-timez
    user: local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: local
  user:
    token: kubeconfig-user-4wntgmk452:f2f6gdnj9nhppsjp86m4jfgxq279m96xqjnh5b7sptt6dvbs6t7cgr
