version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
      - KONG_ADMIN_LISTEN=8001
      - KONG_PROXY_PORT=8000
      
  kong:
    image: docker.io/bitnami/kong:2
    ports:
      - 8001:8001
      - 8000:8000
      - 8443:8443
    environment:    
      - KONG_MIGRATE=yes    
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
volumes:
  postgresql_data:
    driver: local