version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200                 
    networks:
      - graylog
      
  mongo:
    image: mongo:4.0
    networks:
      - graylog
  graylog:
    image: graylog/graylog:3.1
    environment:
        GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    ports:
      - 9000:9000                 
      - 12201:12201/udp
      - 1514:1514
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch 
  
networks:
    graylog:
        driver: bridge